name: Build Kernel

on:
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Install packages
      run: |
        sudo apt update

        sudo apt install -y \
        git curl wget zip unzip bc bison flex \
        build-essential libssl-dev libelf-dev \
        gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi

    - name: Clone kernel source
      run: |
        git clone --depth=1 \
        https://github.com/thanhdien106/6781.git kernel

    - name: Clone NonGKI patches
      run: |
        git clone --depth=1 \
        https://github.com/JackA1ltman/NonGKI_Kernel_Build_2nd.git nongki

    - name: Apply SUSFS patch
      run: |
        cd kernel

        PATCH_FILE="../nongki/Patches/Patch/susfs_patch_to_4.19.patch"

        echo "Patch file:"
        ls -l "$PATCH_FILE"

        patch -p1 < "$PATCH_FILE" || true

    - name: Show reject files
      run: |
        echo "====== REJECT FILES ======"
        find kernel -name "*.rej" || true

        echo
        echo "====== namespace.c.rej ======"
        cat kernel/fs/namespace.c.rej || true

        echo
        echo "====== task_mmu.c.rej ======"
        cat kernel/fs/proc/task_mmu.c.rej || true

    - name: Upload reject files
      uses: actions/upload-artifact@v4
      with:
        name: reject-files
        path: |
          kernel/**/*.rej

    - name: Configure kernel
      run: |
        cd kernel

        export ARCH=arm64
        export SUBARCH=arm64

        make fleur_defconfig

    - name: Build kernel
      run: |
        cd kernel

        export ARCH=arm64
        export SUBARCH=arm64

        make -j$(nproc)

    - name: Upload kernel image
      uses: actions/upload-artifact@v4
      with:
        name: kernel-image
        path: |
          kernel/out/arch/arm64/boot/*