name: Build Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Install packages
      run: |
        sudo apt update

        sudo apt install -y \
          git curl wget zip unzip bc bison flex \
          build-essential ccache libssl-dev \
          libelf-dev gcc-aarch64-linux-gnu \
          gcc-arm-linux-gnueabi python3

    - name: Clone kernel source
      run: |
        git clone --depth=1 \
        https://github.com/thanhdien106/6781.git kernel

    - name: Clone NonGKI patches
      run: |
        git clone --depth=1 \
        https://github.com/JackA1ltman/NonGKI_Kernel_Build_2nd.git nongki

    - name: Clone AnyKernel3
      run: |
        git clone --depth=1 \
        https://github.com/osm0sis/AnyKernel3.git AnyKernel3

    - name: Apply SUSFS patch
      run: |
        cd kernel

        PATCH_FILE="../nongki/Patches/Patch/susfs_patch_to_4.19.patch"

        echo "Patch file:"
        ls -l "$PATCH_FILE"

        patch -p1 < "$PATCH_FILE" || true

    - name: Configure kernel
      run: |
        cd kernel

        export ARCH=arm64
        export SUBARCH=arm64

        make fleur_defconfig

    - name: Build kernel
      run: |
        cd kernel

        export ARCH=arm64
        export SUBARCH=arm64

        make -j$(nproc)

    - name: Copy Image.gz-dtb
      run: |
        cp kernel/out/arch/arm64/boot/Image.gz-dtb \
        AnyKernel3/ || true

    - name: Create zip
      run: |
        cd AnyKernel3
        zip -r9 Kernel.zip ./*

    - name: Upload kernel zip
      uses: actions/upload-artifact@v4
      with:
        name: Kernel
        path: AnyKernel3/Kernel.zip